import type { AnimationDef as AnimationDefType } from '../../types/animation';

export interface AnimationDef {
  directions: number;   // 1 or 8
  fps: number;
  loop: boolean;
  frameCount: number;
  frameKeys: string[][];  // [directionIndex][frameIndex]
}

const DIR_SUFFIXES = ['s', 'sw', 'w', 'nw', 'n', 'ne', 'e', 'se'];

export function buildFrameKeys(unitId: string, action: string, directions: number, frameCount: number): string[][] {
  const result: string[][] = [];
  const dirs = directions === 8 ? DIR_SUFFIXES : ['s'];
  for (const dir of dirs) {
    const frames: string[] = [];
    for (let f = 0; f < frameCount; f++) {
      frames.push(`${unitId}_${action}_${dir}_${f}`);
    }
    result.push(frames);
  }
  return result;
}

// Standard animation stubs — full manifest generated by AnimationManifest.ts
export const ANIMATIONS: Record<string, AnimationDefType> = {
  militia_idle: { directions: 8, fps: 8, loop: true, frameCount: 6, frameKeys: buildFrameKeys('militia', 'idle', 8, 6) },
  militia_walk: { directions: 8, fps: 15, loop: true, frameCount: 10, frameKeys: buildFrameKeys('militia', 'walk', 8, 10) },
  militia_attack: { directions: 8, fps: 15, loop: false, frameCount: 8, frameKeys: buildFrameKeys('militia', 'attack', 8, 8) },
  militia_die: { directions: 1, fps: 10, loop: false, frameCount: 10, frameKeys: buildFrameKeys('militia', 'die', 1, 10) },
};
