export const TILE_WIDTH = 64;
export const TILE_HEIGHT = 32;
export const TICK_MS = 50; // 20 Hz simulation
export const TARGET_FPS = 60;
export const MIN_ZOOM = 0.5;
export const MAX_ZOOM = 2.0;
export const EDGE_SCROLL_THRESHOLD = 20; // px from edge
export const EDGE_SCROLL_MARGIN = 20; // alias for EDGE_SCROLL_THRESHOLD
export const EDGE_SCROLL_SPEED = 300; // world-units per second
export const CAMERA_PAN_SPEED = 300; // pixels per second
